package com.udacity.pricing.domain.price;

import org.springframework.stereotype.Repository;

/**
 * This repository provide a type of data persistence while the web service runs, namely the ID->price pairing generated by the PricingService.
 */
@Repository
public class PriceRepository {

}
